#' IPM to Distance
#'
#' This function takes IPM parameters, generates the IPM, generates the st/age distribution for each IPM,
#' and reports back the distance between the reference IPM and the true IPM. Requires that the stable-st/age
#' distribution be defined in the prior step 
#' 
#' 
#' @param IPM.pre IPM parameter dataframe with NA in parameter values that are unknowns
#' @param observed.stage.dist Dataframe of IPM parameters to be solved (cols = params, rows = samples/particles)
#' @param evaluate.params Parameters to evaluate in the parameter slots in the IPM (IPM.pre)
#' @param i sample/particle to be evaluated. This is the index that gets looped through with an apply function.
#' 
#' @return Distance between the st/age distribution generated by the parameters and the reference distribution
#' @export
#' 


IPMdistance <- function(IPM.pre, observed.stage.dist, evaluate.params, i){
  
  fitted_IPM <- generateIPM(IPM.pre, c(evaluate.params[i,1],
                                       evaluate.params[i,2]))
  
  particle_StageDist <- stableStage(fitted_IPM)
  
  distance <- ShannonDistance(observed.stage.dist,
                              particle_StageDist)
  
  return(distance)
}
